### ISSUE TITLE
建议添加有道智云账号的设置入口

### ISSUE THREAD

**Issue by kerraway** [mjd507/Sublime-Translate#1]
> 建议自己注册一个账号，获取 appKey 和 secretKey，将代码里的对应的 appKey 和 secretKey 换成自己的。（按一个单词 10 个字符来算，新人可免费翻译近 21 万个单词，一天翻译 100 个，可以免费用近 6 年了~）

我看了一下，在 transilate.py 里面找到了我写死的 appKey 和 secretKey ，我用 package control 安装的，没有找到 transilate.py 文件（有可能我没找对地方）。

建议可以通过添加设置的方式添加自己的 appKey 和 secretKey 。

**Comment by mjd507** [comment]
@Gegoiuty  这个建议不错，我已经添加了用户配置的入口，在 Preferences –> Package Settings –> Translate-CN –> Settings - User 下就可以配置 自己的 appKey 和 secretKey （参考 Settings - Default 下的内容）。

之前因为配置原因，通过  package control 下载该插件会变成一个压缩包 Translate-CN.sublime-package，所有你没解压确实是找不到 translate.py 文件的。而现在就可以看到源文件了。

期待你打开 Sublime，等插件自动升级完成后，再体验下最新版的 Translate-CN，配置上你自己的 appKey 和 secretKey ，有问题可以再次反馈~
