### ISSUE TITLE
能不能把翻译的结果复制粘贴出来

### ISSUE THREAD

**Issue by cxwithyxy** [mjd507/Sublime-Translate#2]
对，主要是在给函数或者变量起名字的时候，翻译工具很关键，终于不用自己想到脑袋都破了，但是啊，翻译出来的结果不能复制，要自己重新手打，这就有点难受啊，机械键盘好用也得省点用啊你说是不是

**Comment by mjd507** [comment]
@cxwithyxy 前几天刚添加了把翻译内容设置到剪切板的功能，在弹出的翻译框中，选中一个，就已经复制到剪切板了，在需要的地方粘贴一下就好。
您要不在试一下？

**Comment by cxwithyxy** [comment]
喔，看到了，可以复制粘贴，不错不错，点个赞
