### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by yang7951** [mjd507/Sublime-Translate#6]
选项是灰色的，不能用

**Comment by mjd507** [comment]
@yang7951 选中具体的单词了吗

**Comment by yang7951** [comment]
抱歉，我安装了一个非常规的盗版，新插件都不能用，改用官方的了，不过也有小问题，比如说特殊格式如(ACTIVE_PAD_HONNY, ActivePadHonny,)的不能识别,

**Comment by mjd507** [comment]
嗯，不影响使用就好，接入的第三方翻译服务可能对这些特殊格式的单词不支持。
