### ISSUE TITLE
can't to use

### ISSUE THREAD

**Issue by heshanshanhg3** [mjd507/Sublime-Translate#8]
install translate-CN ,but to use it ,can't select current text or input text。
![image](https://user-images.githubusercontent.com/7931706/66113621-b9e93380-e5ff-11e9-919f-1a991724234f.png)

**Comment by mjd507** [comment]
in my mac, it's ok.  you can select the text in you file and then press `alt ` + `t`.  see it work or not.

by the way, it seems like you installed other translate plugins, may be conflict with this. you can uninstall  others to ensure the problem is still happen or not.
